[package]
name = "mio-worker"
version = "0.1.0"
authors = ["thijsc <thijs@appsignal.com>"]
edition = "2018"

[dependencies]
log = "*"

[dependencies.mio]
version = "0.8"
features = ["os-poll", "net"]

[dev-dependencies]
env_logger = "*"
